### PR TITLE
Update Default Theme

### PR DESCRIPTION
**Pull request by Shiawaseu**

### CODE REVIEW

**Comment by ActualMasterOogway** [comment]
Righttttt

**Comment by Shiawaseu** [comment]
So you gonna merge or not mf

**Comment by ActualMasterOogway** [comment]
> So you gonna merge or not mf

I'd have to review the code first, please dont talk in that tone

**Comment by Shiawaseu** [comment]
MF = My Friend

**Comment by ActualMasterOogway** [comment]
> MF = My Friend

Normally, I wouldn't merge this because you pushed the edit to the Stable and not Experimental, but I'll let it slide this time

**Pull request merged**
